import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import adminUsersRouter from "./adminUsers.js";
import channelsRouter from "./channels.js";
import postsRouter from "./posts.js";
import commentsRouter from "./comments.js";
import schoolReadRouter from "./schoolRead.js";
import schoolAdminRouter from "./schoolAdmin.js";
import uploadsRouter from "./uploads.js";
import progressRouter from "./progress.js";
import membersRouter from "./members.js";
import leaderboardsRouter from "./leaderboards.js";
import likesRouter from "./likes.js";
import searchRouter from "./search.js";
import eventsRouter from "./events.js";
import groupRouter from "./group.js";
import meRouter from "./me.js";
import oauthRouter from "./oauth.js";
import chatsRouter from "./chats.js";
import bookmarksRouter from "./bookmarks.js";
import reactionsRouter from "./reactions.js";
import suggestionsRouter from "./suggestions.js";
import githubReposRouter from "./githubRepos.js";
import recordingsRouter from "./recordings.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminUsersRouter);
router.use(channelsRouter);
router.use(postsRouter);
router.use(commentsRouter);
router.use(schoolReadRouter);
router.use(schoolAdminRouter);
router.use(uploadsRouter);
router.use(progressRouter);
router.use(membersRouter);
router.use(leaderboardsRouter);
router.use(likesRouter);
router.use(searchRouter);
router.use(eventsRouter);
router.use(groupRouter);
router.use(meRouter);
router.use(oauthRouter);
router.use(chatsRouter);
router.use(bookmarksRouter);
router.use(reactionsRouter);
router.use(suggestionsRouter);
router.use(githubReposRouter);
router.use(recordingsRouter);

export default router;
